### PR TITLE
Welcomer

### PR DESCRIPTION
**Pull request by hfgd123**
Added option in the welcomer module to delete the welcome messages of users when they leave within 7 days after their join

### CODE REVIEW

**Review by SCDerox — DISMISSED** [review]
It works - but trying to fetch the message in each channel is kinda inefficient, I would suggest storing the channel-id in the database as well

**Comment by SCDerox** [comment]
If you want, I can merge it as it is, or you could implement the suggested change - in either case, please let me know

**Comment by hfgd123** [comment]
I'll try to implement your suggestion

**Comment by SCDerox** [comment]
FYI: I will push some close-sourced changes we added to the welcomer module, should not interfere with your changes ^^

**Review by SCDerox — APPROVED** [review]
lgtm, thanks for your contribution!

**Pull request merged**
