### PR TITLE
Created Color-Me module

### PR DESCRIPTION
**Pull request by hfgd123**
Created Color-Me module. Requesting review to check for mergablilty

### CODE REVIEW

**Comment by hfgd123** [comment]
Requesting review by @SCDerox

**Review by SCDerox — CHANGES_REQUESTED** [review]
Looking pretty good! 
While I haven't done my usual code-quality check (if you want me to do that, please message me), there are a few issues I encountered when using this module:

- Position of the new role is always at the bottom. Staff should decide below which role the new role should be created (message me if you need help with that)
- Show the user how long the need to wait until their cooldown expires (use `dateToDiscordTimestamp(role.timestamp, 'R'` from helpers.js)
- Entering something random into the color field will show an error about the max-role count, which is not optimal as the input is invalid rather then the role-count is maxed-out

**Comment by SCDerox** [comment]
Also sorry for the rate review, was quite busy working on something :sweat:

**Comment by hfgd123** [comment]
> Show the user how long the need to wait until their cooldown expires (use dateToDiscordTimestamp(role.timestamp, 'R' from helpers.js)

wouldn't this just tell the user, when they edited their role the last time? How can I do math things (english 10/10 :hAA:) with dates?

**Comment by SCDerox** [comment]
Oh, yeah, I am brain dead already (imagine sleeping at night); I will get back to you in about an hour, I have to do some shit irl

**Comment by SCDerox** [comment]
I believe `dateToDiscordTimestamp(new Date(role.timestamp.getTime() + moduleConf['updateCooldown'] * 3600000), 'R')` should work

**Review by SCDerox — APPROVED** [review]
Everything works for me, thanks for your contribution!

**Pull request merged**
